### ISSUE TITLE
存在しないPDFファイル名を指定すると Segmentation fault

### ISSUE THREAD

**Issue by tmtm** [rabbit-shocker/rabbiter#6]
```
% rabbit unexist.pdf
/home/tommy/gems22/gems/rabbit-2.1.8/lib/rabbit/parser/ext/entity.rb:355: warning: duplicated key at line 2409 ignored: "Dagger"
/home/tommy/gems22/gems/rabbit-2.1.8/lib/rabbit/parser/ext/entity.rb:357: warning: duplicated key at line 2411 ignored: "dagger"
[エラー]
存在しません: unexist.pdf
/home/tommy/gems22/gems/rabbit-2.1.8/lib/rabbit/parser/pdf.rb: line 29
   Poppler-INFO **:Syntax warning at position -1: May not be a PDF file (continuing anyway)
/home/tommy/gems22/gems/rabbit-2.1.8/lib/rabbit/parser/pdf.rb: line 29
   Poppler-INFO **:Syntax error at position -1: Couldn't find trailer dictionary
/home/tommy/gems22/gems/rabbit-2.1.8/lib/rabbit/parser/pdf.rb: line 29
   Poppler-INFO **:Syntax error at position -1: Couldn't find trailer dictionary
/home/tommy/gems22/gems/rabbit-2.1.8/lib/rabbit/parser/pdf.rb: line 29
   Poppler-INFO **:Syntax error at position -1: Couldn't read xref table
/home/tommy/gems22/gems/rabbit-2.1.8/lib/rabbit/parser/pdf.rb:29:in `initialize': PDF document is damaged
	 from /home/tommy/gems22/gems/rabbit-2.1.8/lib/rabbit/parser/pdf.rb:29:in `new'
	 from /home/tommy/gems22/gems/rabbit-2.1.8/lib/rabbit/parser/pdf.rb:29:in `parse'
	 from /home/tommy/gems22/gems/rabbit-2.1.8/lib/rabbit/parser.rb:21:in `parse'
〜中略〜
/home/tommy/ruby22/bin/rabbit: [BUG] Segmentation fault at 0x00000000000000
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0001 p:0000 s:0002 E:002080 TOP    [FINISH]


-- Machine register context ------------------------------------------------
 RIP: 0x00007f7c3fe678c0 RBP: 0x000055954104ca30 RSP: 0x00007ffc06269680
 RAX: 0x00cd60e86574c085 RBX: 0x000055954174b730 RCX: 0x0000000000000036
 RDX: 0x000055954174b730 RDI: 0x00007f7c40098628 RSI: 0x0000000000000000
  R8: 0x00007ffc062697d0  R9: 0x000000000000000e R10: 0x0000000000000020
 R11: 0x0000000000000000 R12: 0x00007ffc062698f0 R13: 0x0000000000000001
 R14: 0x00007ffc06269980 R15: 0x000055954104ca30 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/home/tommy/ruby22/bin/ruby(rb_vm_bugreport+0x4ea) [0x55953f2c078a] vm_dump.c:693
/home/tommy/ruby22/bin/ruby(rb_bug_context+0xcb) [0x55953f333abb] error.c:425
/home/tommy/ruby22/bin/ruby(sigsegv+0x3e) [0x55953f23094e] signal.c:879
/lib/x86_64-linux-gnu/libpthread.so.0 [0x7f7c430add10]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 [0x7f7c3fe678c0]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfbc) [0x7f7c3fe70dfc]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f7c3fe7112f]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 [0x7f7c3a052190]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x48) [0x7f7c3fe5c7b8]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 [0x7f7c3a03a122]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x9f) [0x7f7c3fe55f6f]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 [0x7f7c3fe6857e]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfbc) [0x7f7c3fe70dfc]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7f7c3fe7112f]
〜中略〜
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

zsh: abort (core dumped)  rabbit unexist.pdf
```

**Comment by tmtm** [comment]
すいません、プロジェクト間違えました orz

あと、リポジトリ内の最新状態では解消されてました。
