### ISSUE TITLE
「`show_uri': サポートしていない操作です」が発生する

### ISSUE THREAD

**Issue by dai0916** [rabbit-shocker/rabbiter#7]
rabbiter コマンドの実行結果です。

### コマンド実行結果

```
[~] rabbiter --filter "#test"                                                                                                                                                21:18:40
2017-08-30 21:18:50.147 ruby[4198:16060] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
1) このURLにアクセスしてください: https://api.twitter.com/oauth/authorize?oauth_token=X1exXgAAAAAAA6OLAAABXjMUckk
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rabbiter-2.0.3/lib/rabbiter.rb:114:in `show_uri': サポートしていない操作です (Gio::IOError::NotSupported)
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rabbiter-2.0.3/lib/rabbiter.rb:114:in `show_uri'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rabbiter-2.0.3/lib/rabbiter.rb:97:in `setup_access_token'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rabbiter-2.0.3/lib/rabbiter.rb:51:in `setup'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rabbiter-2.0.3/lib/rabbiter.rb:67:in `start'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rabbiter-2.0.3/bin/rabbiter:155:in `main'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rabbiter-2.0.3/bin/rabbiter:177:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.3.1/bin/rabbiter:23:in `load'
	from /usr/local/opt/rbenv/versions/2.3.1/bin/rabbiter:23:in `<main>'
```

### 環境情報
- Mac
OS X El Capitan(10.11.6)

- ruby -v
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`

- rbenv -v
`rbenv 1.0.0`

- gem -v
`2.5.1`

- rabbit -v
`2.2.0`

- rabbiter -v
`2.0.3`

`rabbit`, `rabbiter` は [Mac OS XでHomebrewを使ったインストール方法](https://rabbit-shocker.org/ja/install/homebrew.html) にてインストールしています。

**Comment by kou** [comment]
直して2.0.4としてリリースしたので試してみてください！

**Comment by dai0916** [comment]
2.0.4で直りました！
対応ありがとうございます！
